FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
RUN mkdir /api_gateway
WORKDIR /api_gateway
COPY Gemfile /api_gateway/Gemfile
COPY Gemfile.lock /api_gateway/Gemfile.lock
RUN bundle install
COPY . /api_gateway

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
