---
- name: Ensure server is up to date
  become: true
  apt:
           update_cache: yes
           #upgrade: full

- name: Install VIM
  become: true
  apt:
           name: vim
           update_cache: yes
           state: latest

#### Copy ssh conf file ####

- name: Copy sshd_config to vm
  become: true
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: Reload ssh service
  become: true
  service:
    name: ssh
    state: reloaded

##############################
